name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.0.1)'
        required: true
        type: string

permissions:
  contents: write  # Required for creating releases

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # Use the latest stable version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: |
          flutter build windows --release --build-name=${{ inputs.tag }} --build-number=${{ inputs.tag }}

      - name: Package artifact
        run: |
          mkdir -p release
          cp -R build/windows/x64/runner/Release/ release/win
          cd release
          7z a -tzip repo-manager-windows.zip win/*
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: release/repo-manager-windows.zip
          retention-days: 1

  build-macos:
    runs-on: macos-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # Use the latest stable version

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS
        run: |
          flutter build macos --release --build-name=${{ inputs.tag }} --build-number=${{ inputs.tag }}

      - name: Package artifact
        run: |
          mkdir -p release
          cp -R "build/macos/Build/Products/Release/Repo Manager.app" release/macos/
          cd release
          zip -r repo-manager-macos.zip macos/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: release/repo-manager-macos.zip
          retention-days: 1

      - name: Generate changelog
        id: changelog
        run: |
          # Try to get the previous tag (excluding the input tag)
          CURRENT_TAG=${{ inputs.tag }}
          LATEST_TAG=$(git describe --tags --abbrev=0 --exclude $CURRENT_TAG 2>/dev/null || echo "")
          if [ -z "$LATEST_TAG" ]; then
            # No previous tags, get all commits up to current tag
            CHANGELOG=$(git log --pretty="* %s (%h)" $CURRENT_TAG)
          else
            # Get commits between last tag and current tag
            CHANGELOG=$(git log --pretty="* %s (%h)" $LATEST_TAG..$CURRENT_TAG)
          fi
          # Escape newlines for GitHub output
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos]
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-release
          path: ./

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-release
          path: ./

      - name: Debug release directory contents
        run: |
          ls -la
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: Release ${{ inputs.tag }}
          body: |
            ## Changes
            ${{ needs.build-macos.outputs.changelog }}

            ## Artifacts
            - **repo-manager-windows.zip**: Windows executable and dependencies
            - **repo-manager-macos.zip**: macOS application bundle
          files: |
            repo-manager-windows.zip
            repo-manager-macos.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}